### ISSUE TITLE
Request: some way to chat you up about objectify

### ISSUE THREAD

**Issue by mistergibson** [drum445/objectify#1]
I'm considering using objectify but on occasion I have questions. Are you on Gitter or IRC? I can be reached in Gitter here: https://gitter.im/crystal-lang/crystal-db as @mistergibson .

Some background:

I am new to Crystal and coming from Ruby. I have used Sequel for Ruby extensively for years now and have found no equal in the ORM sector frankly and I've reviewed many. If I can find anything that even comes close to that in Crystal Shard Universe I'm contented. However, I notice that a lot of the Crystal ORMs seem to *assume* you are only going to use ONE db (like ActiveRecord does). My use cases ALWAYS require multiple dbs and I need to sync data across drivers and technologies. As I said, I'm new to Crystal but if there is anything I can do to help I'll give it my best shot. I really want to see a Sequel in Crystal if it is possible.

Thanks,

G.

**Comment by drum445** [comment]
I am also available on that gitter room, cheers
